# Config file for automatic testing at travis-ci.org

dist: focal
language: python
python:
  - 3.9-dev
  - 3.8
  - 3.7
  - 3.6
  - 2.7
  - pypy3
  - pypy

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: mdNz2jUQOvyU4WHpiYYYuo3+nfyl3DwFn/T9asoZldLK4ffPIZ1HSgE+5U0UwnGbPjcgAUwY1eVGK8Z6jqfyWSAuoFe+bsLuPzHNAe49w39smVLC4bBCTJyVPqLblDe6m2xlHIbACLn+GNwVTYuu2kHP4aLcFqOcitO94mGPAErzFo795/iiMU1XvXGTTBGulIx5GqRRTPV1B0CVN4Ebwk2k04NSvzfdUUYH9jNvidSGT5Xjeb1nxPyrls+BtniEVmpgL2SL8WZV9lFOVuTrInl7eje42ASwDucQ1ZJgnU8BIqbfMGGfzLgQAIrSppygSSlf83T4jsZuN1gOodKb4uyefOLk1YouiJt+Y/Tyc8Mejc6qvYi/hHrOCHH1JpPCDY7rLpteQd98MvBc3faiTkqy/zlrp8MrKDonkfh+NmBQp79CfBP694BFBs2SQvIN2t4pY28kTdXFizp9e9arlWpqznxy3132ydFgCzUcYAOEWeltb9z87PwpuyMaGXnimg+b95xCOiywaxzngupdfFQIYFDlZFOZQRC1Sk4JealGDQBJc0pdKe/SfXPUSdJL9cD/0U5ugI6fgKWUIZYtfWjf8Uwm8FiOELqxbd7dMrPYiANric91z+P2ZEDfl29+2rUt9I5Kgjk4GAcMKClMBbBzY2ugW19lcor/1RdL3Ug=
  on:
    tags: true
    repo: tailsdotcom/boolrule
    python: 3.7
