# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: spjwebster
  password:
    secure: c5+mBUsu1w9m4DqnK/qPwd2XeoCbhFxo0lzA8bzbrXCszL+78BQV3mQJM4Tlw2CMlf56eOKMLOJFRkHp1iumNgh2Jh8cvtitmCHD0jFwzvpBa3y/6nY+f0RiB9WMRIdODUABa0i/K74b+XwoYZk2vaGJwgI9G7nTsx/Zs/bxxNy/OsY6ucu+o45fitgaANY23T2srtlkhjj8r4FpXpkTSvCbhL17qKALA+AYHfkk1H4n5Fc/qV1M0qduWjg2JvKMFpPoAGr4P77gubrhGWZTPn12HH0tbjz/1Svo2Te228OEV8/vE4H3Z40+xFnMq9W3ui4FwFcG3Q9KJAscPJVZ4OoWGUSX7ifGpQRhGFwxWSs9Iml7CZL9P8KGzfK8CTQU3wiGXZQPxeoknH4IN7dlc3d5deAmz/H6CXf20TKN7haSWvz7/rBhtPDUHdB80tdSux12uy4n5HKVlaBxJ7tsd4wOPUsWIipfP4xBSbfqO7l5k2iIDQPgd67isbm0FkG1VxO8SEQBs2DPCmeO47iMEVwtyyE8hQT4+3fKZZQKrTZ97KigBhD9PsnyxmWoIt/QkE+yCvelcyEigzwXUgjUvqfrxmu2jguNgqVyUYAviVQb1pL97dcV1dzPJsbY7pL6KLMRsYOP2wMGvTWJANyM1Uiq6euaP/G3QZgrCTmUg+I=
  on:
    tags: true
    repo: tailsdotcom/boolrule
    python: 3.7
